### ISSUE TITLE
First line of description not always showing

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/working-class-history#60]
**Bug**
First line of description not showing in main index for article Test 2021.11.10 (row 1009)

Notion 12

https://www.notion.so/90557c58fc6d459f87bf661a65ed9d25?v=7b42347d0d28441fbb7a4301f14c567c

**Comment by fadeomar** [comment]
this is because the user doesn't provide `preview_text`, which cause this issue, I've fixed this by adding default value 'N/A' if `preview_text` is not provided
