### ISSUE TITLE
Source showing without spaces

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/working-class-history#68]
The source listed in this article has no spaces for some reason. Had a look in the baserow and the source in that looks fine so not sure what the issue is

Notion 24

https://www.notion.so/90557c58fc6d459f87bf661a65ed9d25?v=7b42347d0d28441fbb7a4301f14c567c

**Comment by fadeomar** [comment]
this is because the sources displayed on `p` tag, that means will treat all text that comes from sources will show as a paragraph so I need to update the field to become rich text like description, is that right @thejoefriel ?

**Comment by thejoefriel** [comment]
Fixed this
